name: quickumls_data_building
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - spacy
  # This is for leveldb (and QuickUMLS)
  - libiconv
  - python-leveldb
  - numpy>=1.8.2
  - spacy>=1.6.0
  - unidecode>=0.4.19
  - nltk>=3.3
  - nb_conda
  - pip
  - pip:
      # Recent quickumls_simstring still fails, so run these instead:
      # pip install git+https://github.com/burgersmoke/simstring.git
      # pip install --no-deps git+https://github.com/burgersmoke/quickumls.git@issue_60_spacy_entity_overlap
      #- quickumls_simstring>=1.1.5r1
      - unqlite>=0.8.1

