name: quickumls_data_building
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - spacy
  - leveldb
  - numpy>=1.8.2
  - spacy>=1.6.0
  - unidecode>=0.4.19
  - nltk>=3.3
  - pip
  - pip:
      - quickumls_simstring>=1.1.5r1
      - unqlite>=0.8.1
      # this needs to be run after install since the below is not working:
      # pip install --no-deps quickumls
      # now we can install this with no dependencies
      #- --no-deps
      #- quickumls>=1.4.0

